// This file is automatically generated. Do not edit it directly.
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseExt } from "@/lib/supabase";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = supabaseExt as SupabaseClient<Database>;
